### ISSUE TITLE
[Bug] Packet receiver and sender do not compile

### ISSUE THREAD

**Issue by kaiserdj** [Alph4rd/darkorbit_packet_dumper#1]
In some of the latest darkorbit updates it has stopped working

```python
PS  > python.exe .\packet_dumper.py
[+] Found process74220.
[!] Press <Enter> to stop.[+] CreateString  : 0x7ffa7545b3a0
[+] Json stringify     : 0x7ffa7551d490
[+] Found verifyJit: 0x7ffa75503710
[+] setproperty     : 0x7ffa754c8630
[+] getproperty     : 0x7ffa754c7ad0
[+] Fake json object   : 0x23606e73ad0
[+] Main address       : 0x359b3ec6d70
[+] ConstPool address  : 0x359b2f496d0
[+] AvmCore address    : 0x4cdb2de0000
[+] Namespace list     : 0x236739f5378
[+] Packet handler     : 0x359b5b97168
[+] Packet sender      : 0x359b5b96e00
[+] Packet receiver is not compiled, waiting for it
[+] Packet sender is not compiled, waiting for it
```

**Comment by Alph4rd** [comment]
Fixed, thanks!

**Comment by tram98** [comment]
@Alph4rd the issue has reappeared apparently. I am using the script with the client by @kaiserdj
_______________________________
EDIT: The current script of yours works. The client does not have the most recent one as it seems @kaiserdj

**Comment by kaiserdj** [comment]
> @Alph4rd the issue has reappeared apparently. I am using the script with the client by @kaiserdj
> 
> EDIT: The current script of yours works. The client does not have the most recent one as it seems @kaiserdj

Yes, it is updated in the repository, only that an updated version has not yet been released

https://github.com/kaiserdj/Darkorbit-client/commit/b96d2ab839414e0afd1283591fe4126093486d77
